name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build & test (TestNG + Cucumber)
        run: |
          mvn -B -ntp clean test \
            "-DsuiteXmlFile=testng.xml" \
            "-Dretry.maxAttempts=2"

      
      - name: Upload reports (Cucumber/TestNG)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            cucumber-report.html
            cucumber.json
            target/surefire-reports/**
            target/cucumber-reports/**
          if-no-files-found: warn
